
server:
  port: 8080
  http2:
    enabled: true
  shutdown: graceful
  undertow:
    threads:
      io: 8
      worker: 64
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: boot-template
  profiles:
    active: prod
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.100:3306/bootapp?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&tcpKeepAlive=true&maintainTimeStats=false
    username: root
    password: root123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ${spring.application.name}-hkpool
      maximum-pool-size: 10
      minimum-idle: 10
      max-lifetime: 25200000
      keep-alive-time: 1800000
      connection-timeout: 1000
      validation-timeout: 300
  data:
    redis:
      host: 192.168.3.50
      port: 6379
      password: 123456
      database: 0
      jedis:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 10
          max-wait: 1000
          time-between-eviction-runs: 300

